name: Build Step

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.20.0]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build Application
        run: npm run build --if-present

  test-stage:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Tests
        run: echo "Running Tests"

  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    needs: ['build', 'test-stage']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.G_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: |
            dragos93/gitops01:${{ github.sha }}
            ghcr.io/dragos93/gitops01:${{ github.sha }}
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Output Image Digest
        run: echo ${{ steps.build-and-push-docker-image.outputs.digest }}

  update-manifest-stage:
    runs-on: ubuntu-latest
    needs: ['build-and-push-docker-image']

    steps:
      - name: Checkout Infra Repository
        uses: actions/checkout@v3
        with:
          repository: dragos1993/gitops01/infra
          ref: main
          token: ${{ secrets.G_TOKEN }}

      - name: Setup Git Config
        run: |
          git config --global user.email "vrinceanu.dragos24@yahoo.com"
          git config --global user.name "dragos1993"

      - name: Update Deployment Manifest
        run: |
          echo ${{ github.sha }}
          sed -i "s#IMAGE_PLACEHOLDER#dragos93/gitops01:${{ github.sha }}#g" deployment.yaml
          git add deployment.yaml
          git commit -m "Update image for ${{ github.sha }}"
          git push origin main