name: Build Step

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.20.0]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
  
  test-stage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Running Tests
        uses: actions/checkout@v3
      - run: echo "runningngngngngn"

  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    #run only when code is compiling and test are passing
    runs-on: ubuntu-latest
    needs: ['build', 'test-stage']

    #steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

        #setup Docer build action
      - name: Set up Docker Buildx
        id: Buildx
        uses: docker/login-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.G_TOKEN }}

      - name: Build image and push to Docker Hub and GitHub Container registry
        uses: docker/build-push-action@v2
        with: 
          # relative path to the place where source code with Dockerfile is located
          context: ./
          # Note: tags has to be all lower-case
          tags: /
            dragos93/gitops01:${{ github.sha }}
            ghcr.io/dragos93/gitops01:${{ github.sha }}
          #build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  update-manifest-stage:
    runs-on: ubuntu-latest
    needs: ['build-and-push-docker-image']
    steps:
      - uses: actions/checkout@v3
        with:
          repository: dragos1993/gitops01/infra
          ref: 'main'
          token: ${{ secrets.G_TOKEN }}
      - name: setup git config
        run: /
          git config --global user.email "vrinceanu.dragos24@yahoo.com"
          git config --global user.name "dragos1993"
          echo ${{ github.sha }}
          sed -i "s#${{ github.actor }}.*${{ github.actor }}/gitops01:${{ github.sha }}#g" deployment.yaml
          git add -A
          git commit -am "Update image for - ${{ github.sha }}"
      - run: echo ${{ github }}
      - run: git push origin main